CREATE TABLE treatment (_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, duration TEXT, breakfast BOOLEAN, lunch BOOLEAN, dinner BOOLEAN, sleep BOOLEAN);
CREATE TABLE pressure (_id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT, pressure TEXT);
CREATE TABLE glucose (_id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT, glucose TEXT);